### ISSUE TITLE
npm test failure NodeJS v10.2.0 and TypeScript Version 3.4.3

### ISSUE THREAD

**Issue by vprdnew** [shah/uniform-resource#1]
I ran on NodeJS v10.2.0 and TypeScript Version 3.4.3: 
   
    npm test 
    
I see the following errors, please investigate this.
```
 stack:
 ReferenceError: BigInt is not defined
     at createLongLongConversion (/home/vishnu/Projects/uniformresource/uniform-resource/node_modules/webidl-conversions/lib/index.js:158:51)
     at Object.<anonymous> (/home/vishnu/Projects/uniformresource/uniform-resource/node_modules/webidl-conversions/lib/index.js:220:24)
     at Module._compile (internal/modules/cjs/loader.js:702:30)
     at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
     at Object.require.extensions.(anonymous function) [as .js] (/home/vishnu/Projects/uniformresource/uniform-resource/node_modules/ts-node/src/index.ts:851:44)
     at Module.load (internal/modules/cjs/loader.js:612:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
     at Module.require (internal/modules/cjs/loader.js:650:17)
     at require (internal/modules/cjs/helpers.js:20:18)
     at Object.<anonymous> (/home/vishnu/Projects/uniformresource/uniform-resource/node_modules/jsdom/lib/jsdom/browser/Window.js:3:27)
     at Module._compile (internal/modules/cjs/loader.js:702:30)
     at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
     at Object.require.extensions.(anonymous function) [as .js] (/home/vishnu/Projects/uniformresource/uniform-resource/node_modules/ts-node/src/index.ts:851:44)
     at Module.load (internal/modules/cjs/loader.js:612:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
```

**Comment by shah** [comment]
@vprdnew please try it on at least NodeJS 12.x or 14.x and the latest version of TypeScript that works with React/React Admin.
